# Generated by Django 5.1.3 on 2024-11-15 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_open_date', models.DateField()),
                ('registration_close_date', models.DateField()),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('competition_type', models.CharField(choices=[('tournament', 'Tournament'), ('competition', 'Competition')], default='competition', max_length=100)),
                ('price', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=False)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='competition_banners/')),
                ('rules', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category')),
                ('parent_tournament', models.ForeignKey(blank=True, help_text='Specify the tournament if this is a round/competition within a tournament.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_competitions', to='dashboard.competition')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('sound', 'Sound'), ('music', 'Music')], max_length=10)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='competition_videos/')),
                ('sound_file', models.FileField(blank=True, null=True, upload_to='competition_sounds/')),
                ('music_file', models.FileField(blank=True, null=True, upload_to='competition_music/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='dashboard.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='competition_videos/')),
                ('is_qualified_for_next_round', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='dashboard.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.register')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('eliminated_percentage', models.PositiveIntegerField(default=20)),
                ('max_participants', models.PositiveIntegerField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='dashboard.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_rounds', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_open_date', models.DateField()),
                ('registration_close_date', models.DateField()),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='tournament_banners/')),
                ('rules', models.TextField(blank=True, null=True)),
                ('price', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.tournament'),
        ),
    ]
