# Generated by Django 5.1.3 on 2024-11-15 10:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='rules',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rules',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
