# Generated by Django 5.1.3 on 2024-11-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover-images/'),
        ),
        migrations.AddField(
            model_name='register',
            name='points',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile-images/'),
        ),
        migrations.AddField(
            model_name='register',
            name='votes',
            field=models.BigIntegerField(default=0),
        ),
    ]
