# Generated by Django 5.1.2 on 2024-11-11 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_open_date', models.DateField()),
                ('registration_close_date', models.DateField()),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('competition_type', models.CharField(choices=[('tournament', 'Tournament'), ('competition', 'Competition')], default='competition', max_length=100)),
                ('price', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=False)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='competition_banners/')),
                ('rules', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category')),
            ],
            options={
                'verbose_name_plural': 'Competitions',
            },
        ),
        migrations.CreateModel(
            name='CompetitionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('sound', 'Sound'), ('music', 'Music')], max_length=10)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='competition_videos/')),
                ('sound_file', models.FileField(blank=True, null=True, upload_to='competition_sounds/')),
                ('music_file', models.FileField(blank=True, null=True, upload_to='competition_music/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='dashboard.competition')),
            ],
        ),
    ]
