# Generated by Django 5.1.2 on 2024-11-11 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='parent_tournament',
            field=models.ForeignKey(blank=True, help_text='Specify the tournament if this is a round/competition within a tournament.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_competitions', to='dashboard.competition'),
        ),
    ]
