# Generated by Django 5.1.3 on 2024-11-15 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=50, unique=True)),
                ('likes_required', models.PositiveIntegerField()),
                ('award', models.URLField(blank=True, null=True)),
                ('border_design', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BigIntegerField(default=0)),
                ('current_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='levels.stage')),
            ],
        ),
    ]
