# Generated by Django 5.1.2 on 2024-10-24 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_userprofile_register'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
